version: "3.7"

services:
  sfu:
    image: eyevinntechnology/wrtc-sfu:latest
    network_mode: "host"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
    environment:
      - HTTP_PORT=8280
    logging:
      driver: "local"
      options:
        max-size: 10m
  ingest:
    image: eyevinntechnology/wrtc-origin:latest
    depends_on:
      - sfu
    network_mode: "host"
    environment:
      - PORT=8200
      - EXT_PORT=8200
      - SMB_URL=http://localhost:8280/conferences/
      - WHPP_API_URL=http://localhost:8201/api
      - WHPP_EGRESS_URL=http://localhost:8201/whpp